pool:
  name: GP IT Futures AKS Build Agents
steps:
- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)\scripts'
  inputs:
    SourceFolder: SQL
    TargetFolder: '$(build.artifactstagingdirectory)\scripts'
    CleanTargetFolder: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: scripts'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)\scripts'

jobs:
- job: dockerBuildAndPush
  displayName: Build and push docker containers to the acr
  steps:
  - task: DockerInstaller@0
    inputs:
      dockerVersion: '18.09.9'

  - task: DockerCompose@0
    displayName: 'Build: Dev'
    inputs:
      containerregistrytype: 'Azure Container Registry'
      azureSubscription: 'NHSAPP-BuyingCatalogue (Non-Prod)'
      azureContainerRegistry: '{"loginServer":"gpitfuturesdevacr.azurecr.io", "id" : "/subscriptions/7b12a8a2-f06f-456f-b6f9-aa2d92e0b2ec/resourceGroups/gpitfutures-dev-rg-acr/providers/Microsoft.ContainerRegistry/registries/gpitfuturesdevacr"}'
      dockerComposeFile: '**/docker-compose-build.yml'
      action: 'Build services'
      additionalImageTags: '$(Build.BuildNumber)'
      includeSourceTags: true

  - task: DockerCompose@0
    displayName: 'Push: Dev'
    inputs:
      containerregistrytype: 'Azure Container Registry'
      azureSubscription: 'NHSAPP-BuyingCatalogue (Non-Prod)'
      azureContainerRegistry: '{"loginServer":"gpitfuturesdevacr.azurecr.io", "id" : "/subscriptions/7b12a8a2-f06f-456f-b6f9-aa2d92e0b2ec/resourceGroups/gpitfutures-dev-rg-acr/providers/Microsoft.ContainerRegistry/registries/gpitfuturesdevacr"}'
      dockerComposeFile: '**/docker-compose-build.yml'
      action: 'Push services'
      additionalImageTags: '$(Build.BuildNumber)'
      includeSourceTags: true