version: '3.5'

services:

  nhsd.buyingcatalogue.datamodel:
    image: ${REGISTRY:-nhsd}/buying-catalogue/debug-db:${TAG:-latest}
    container_name: nhsd_datamodel
    build:
      context: .
      dockerfile: Dockerfile
